[package]
name = "pobsd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = "0.26"
serde = "1"
serde_json = "1"
serde_derive = "1"
clap = "4"
unveil = "0.3"
pledge = "0.4"
confy = "0.5"
igdb-rs = { path = "../../igdb-rs", optional = true}
pobsd-parser = { path = "../pobsd-parser" }
